tasks:
  run-tests:
    name: Run Tests
    command: |
      sudo apt-get update
      sudo apt-get install -y maven default-jdk
      mvn -v
      mvn test -DsuiteXmlFile=testng.xml
    triggeredBy:
      - postEnvironmentStart